# Generated by Django 4.2.7 on 2023-11-29 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vol', models.CharField(max_length=10)),
                ('compagnie_aerienne', models.CharField(max_length=50)),
                ('origine', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('date_depart', models.DateTimeField()),
                ('date_arrivee', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDesVols.vol')),
            ],
        ),
    ]
