# Generated by Django 4.2.7 on 2023-11-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDesUtilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
